# Site Metadata
title: "Justin Kindrix's Blog"
email: "contact@jkindrix.dev"
description: >-
  Insights, tutorials, and updates from Justin Kindrix on software development, architecture, and personal projects.
baseurl: "" # Leave empty if the blog is not in a subdirectory
url: "https://blogs.jkindrix.dev" # Full URL to your site
twitter_username: "jkindrix"
github_username: "jkindrix"

# Build Settings
theme: minima
plugins:
  - jekyll-feed        # Generates RSS feed
  - jekyll-seo-tag     # Improves SEO with meta tags
  - jekyll-sitemap     # Generates a sitemap for search engines
  - jekyll-paginate    # Adds pagination support
  - jekyll-archives    # Provides archive pages by year, month, etc.

# Environment-specific settings
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
  - README.md
incremental: true # Enables incremental regeneration for faster local builds

# Sass/CSS
sass:
  style: compressed # Compresses CSS output for faster loading

# Default Front Matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Justin Kindrix"
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"

# Collections
collections:
  tutorials:
    output: true
  projects:
    output: true

# URLs & Permalinks
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"

# Markdown Options
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
  auto_ids: true
  syntax_highlighter: rouge

# Development & Production Environment Setup
environments:
  development:
    url: "http://localhost:4000"
    show_drafts: true
  production:
    url: "https://blogs.jkindrix.dev"
